name: CI HTML Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint on index.html
        run: htmlhint index.html
