name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare report files
        run: |
          touch report_html.html report_md.md report_json.json
          chmod a+w report_html.html report_md.md report_json.json

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://katakuriop123.github.io/belajar-github-actions/'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'
        env:
          GITHUB_TOKEN: ''        # Menonaktifkan auto upload
          GITHUB_ACTIONS: 'false' # Menonaktifkan auto create issue

      - name: Upload ZAP Scan Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.run_id }}
          path: |
            report_html.html
            report_md.md
            report_json.json
